name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install protobuf
        run: ci/install-protobuf.sh
        shell: bash
        env:
          PROTOBUF_VERSION: 3.19.4
      - name: Build
      - uses: actions/checkout@v3
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
