name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache protobuf
      uses: actions/cache@v2
      with:
        key: pb-linux-3.19.4
        path: ~/pb
      env:
        cache-name: pb

    - name: Install protobuf
      run: ci/install-protobuf.sh
      shell: bash
      env:
        PROTOBUF_VERSION: 3.19.4

    - name: Protoc check
      run: protoc --version
      shell: bash

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
